### ISSUE TITLE
Single newline in markdown doesn't cause a single newline

### ISSUE THREAD

**Issue by ulyssesp** [Uncodin/bypass#141]
If there's a single newline in the markdown it should be parsed as a single newline in the Bypass text, but instead it gets turned into a space because of 
```
if (element.size() == 0
    && element.getParent() != null
    && element.getParent().getType() != Type.BLOCK_CODE) {
    text = text.replace('\n', ' ');
}
```

**Comment by KynoYang** [comment]
Is anyone working on this issue?

**Comment by KynoYang** [comment]
Sorry. 
Maybe “When you do want to insert a 
break tag using Markdown, you end a line with two or more spaces, then type return” is the answer.

**Comment by ulyssesp** [comment]
This was merged so I'm going to close it now.

**Comment by georgbachmann** [comment]
Is there a way to tell the Android Version how big the paragraph spacing should be? iOS has `paragraphSpacing` but I can't seem to find an attribute for Android?!?
Cause then I can simply replace a single \n with two and reduce the paragraph spacing...
