### ISSUE TITLE
Bypass via Cocoapods not compile in Swift project

### ISSUE THREAD

**Issue by mhergon** [Uncodin/bypass#180]
Hi,

Anyone know how to compile Swift project with Bypass library added?
I have many errors like this...

![captura de pantalla 2015-06-08 a las 12 33 21](https://cloud.githubusercontent.com/assets/621373/8032943/9732a850-0dda-11e5-83cc-79fb943ec124.png)

**Comment by justinswart** [comment]
Also had this issue, answer is here: http://stackoverflow.com/a/32781423/2271759

**Comment by mhergon** [comment]
@justinswart Thanks!
