### ISSUE TITLE
Is there Image support working in Android?

### ISSUE THREAD

**Issue by victorlaerte** [Uncodin/bypass#214]
I'm trying to load a simple markdown with an Header and Image, but the image is never rendered.
I tried many other options but still not working, am I doing something wrong, or is there a issue?

```java
String markdownStr = "# Testing Markdown\n" +
	"\n" +
	"![surf](http://www.adesl.pt/images/outras-provas/surf.jpg)";

TextView markdownTxtView = (TextView) findViewById(R.id.markdown);

Bypass bypass = new Bypass(getApplicationContext());

CharSequence charSequence = bypass.markdownToSpannable(markdownStr, new Bypass.ImageGetter() {
	@Override
	public Drawable getDrawable(String source) {
		//TODO: get drawable from source

		Drawable drawable = getApplicationContext().getResources().getDrawable(R.drawable.test);

		return drawable;
	}
});

markdownTxtView.setText(charSequence);
```

**Comment by victorlaerte** [comment]
Hey, @dlew maybe you could give me a hint.

**Comment by dlew** [comment]
Not sure why it's not working for you. For us, we're returning a wrapped `Drawable` that loads itself asynchronously via Picasso. It's not perfect but it does work.

**Comment by Jawnnypoo** [comment]
For reference, this is a library I created to work with `bypasses` a fork of this library that allows for gradle dependency on Bypass, and will load images using Picasso

https://github.com/Commit451/BypassPicassoImageGetter

You could either include that and switch over to using [bypasses](https://github.com/Commit451/bypasses) or just copy out the code from that lib. 

Just an FYI though, I would recommend potentially switching over to [commonmark-java](https://github.com/atlassian/commonmark-java) as it has better support than bypass in my opinion. If you did so, the code for loading images would still be very similar to the BypassPicassoImageGetter library

Hope that helps @victorlaerte

**Comment by victorlaerte** [comment]
by adding bellow code it works:
`drawable.setBounds(0, 0, drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight());`

@Jawnnypoo I've notice that in Thomas Moerman's stackoverflow question he did the same.
